services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: # RabbitMQ default port(5672) and management UI(15672) port
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
